### ISSUE TITLE
Branch passwords don't retain plaintext value

### ISSUE THREAD

**Issue by ericvoshall** [koslib/terraform-provider-planetscale#12]
I am using the `planetscale_database_branch_password` to manage connection strings for my application, but subsequent runs after creation have the `plaintext` property as null, resulting in a connection string with no password.

My resource definition:
```hcl
resource "planetscale_database_branch_password" "app_password" {
  branch       = planetscale_database_branch.dev.name
  database     = planetscale_database_branch.dev.database
  name         = "app"
  organization = planetscale_database_branch.dev.organization
  role         = "readwriter"
}
```

My output definition:

```hcl
output "app_database_connection_string" {
  value     = format("mysql://%s:%s@aws.connect.psdb.cloud/%s?sslaccept=strict", planetscale_database_branch_password.app_password.username, planetscale_database_branch_password.app_password.plaintext, planetscale_database_branch_password.app_password.database)
  sensitive = true
}
```

First run of `terraform apply` creating the resource results in output (`xxx` for redaction):
```
app_database_connection_string = "mysql://x7o7anqlq5pstk6oyo4o:pscale_pw_xxx@aws.connect.psdb.cloud/xxx?sslaccept=strict"
```

Any subsequent runs of `terraform apply` result in output (`xxx` for redaction):
```
Changes to Outputs:
  ~ app_database_connection_string    = "mysql://x7o7anqlq5pstk6oyo4o:pscale_pw_xxx@aws.connect.psdb.cloud/xxx?sslaccept=strict" -> "mysql://x7o7anqlq5pstk6oyo4o:@aws.connect.psdb.cloud/xxx?sslaccept=strict"
```

I am currently working around this by recreating the passwords each time:
```hcl
resource "null_resource" "always_run" {
  triggers = {
    timestamp = "${timestamp()}"
  }
}

resource "planetscale_database_branch_password" "app_password" {
  branch       = planetscale_database_branch.dev.name
  database     = planetscale_database_branch.dev.database
  name         = "app"
  organization = planetscale_database_branch.dev.organization
  role         = "readwriter"

  lifecycle {
    replace_triggered_by = [null_resource.always_run]
  }
}
```

I use other providers to create client secrets/passwords and they retain the value across runs of `terraform apply` so I assume this is a bug, but I am not a Terraform expert.

Thanks!

**Comment by koslib** [comment]
Interesting! Thanks for reporting, I’ll circle back with updates as soon as I can!

**Comment by jpedroh** [comment]
I've faced the same issue and tried to debug it a little.

This seems like a bug in Planetscale SDK itself. Indeed, if you try to perform the plain HTTP Request for the Planetscale endpoint to retrieve passwords as described here https://api-docs.planetscale.com/reference/get-a-password you will get plain_text with null, which results in an empty string within terraform. Don't think there's much we can do here other than using the workaroud til this is fixed on they side?

**Comment by ericvoshall** [comment]
I think it should be possible for Terraform to maintain the password in its state - I use similar resources for managing client secrets in Azure and those are not visible after they are created.

**Comment by jpedroh** [comment]
Indeeed @ericvoshall . Perhaps a possible solution for this issue would be to remove these lines, which update the state during the read phase?

https://github.com/koslib/terraform-provider-planetscale/blob/889e7b5c8f553dbe78d20ca837db62368e69babd/planetscale/database_branch_password_resource.go#L168

I'll draft a PR with this possible fix.

**Comment by koslib** [comment]
This is one idea @jpedroh and I'm willing to try it. I am not sure if that would cause any other implications though 🤔 I can take a closer look a bit later in the day and make an RC release to try this out if this works out for you?

**Comment by jpedroh** [comment]
@koslib Yep, I'm open to test a RC and provide some feedback on it! Please, let me know once it's available :)

**Comment by ericvoshall** [comment]
I'm open to test as well.

**Comment by koslib** [comment]
Merged #13 and published [v0.6.0](https://registry.terraform.io/providers/koslib/planetscale/0.6.0) pre-release so that we can test it out! 

_ps: sadly the terraform registry does not support `-rc` suffixes in releases/tags so had to fallback to a `x.y.z` pre-release instead_

**Comment by jpedroh** [comment]
Gave it a try now and the result seems promising. I've removed the workaround suggested by Eric and ran a terraform plan right after a successful creation. No changes were detected. With the previous version, 0.5.2, doing this would result in a recreation of other resources that depended on the branch password.

**Comment by koslib** [comment]
Nice! Let's keep this issue open to monitor it for a while and report back if we encounter any issues - thanks all for your help!

**Comment by ericvoshall** [comment]
Looking good on my end too, thanks @koslib and @jpedroh!
