### ISSUE TITLE
`planetscale_database` resource does not accepts GCP database regions.

### ISSUE THREAD

**Issue by 01Joseph-Hwang10** [koslib/terraform-provider-planetscale#17]
`planetscale_database` resource does not accept GCP region values (e.g. gcp-asia-northeast3, gcp-us-east4, ...) as a value of `region` key. Seems like the validator located at [here](https://github.com/koslib/terraform-provider-planetscale/blob/main/planetscale/database_resource.go#L73-L84) keeps those GCP region values to be passed into the API Client. If this is an expected behavior, please let me know :)
<img width="1032" alt="스크린샷 2023-12-04 오전 12 24 03" src="https://github.com/koslib/terraform-provider-planetscale/assets/72839543/7655535b-92b6-4063-9ce5-8f97e47ae97b">

**Comment by koslib** [comment]
Thanks for reporting! Would you have time to look into it and submit a PR potentially? Otherwise I'll add it in my todo list and will get to it once I can get to it :(

**Comment by 01Joseph-Hwang10** [comment]
It sounds very interesting! I'll submit the PR regarding this issue. Please let me know if there's any guidelines to follow when submitting the PR.

**Comment by koslib** [comment]
No specific contribution guidelines just yet in this repo - just follow along the codebase's structure and it should be fine :D Thanks!
